return PlaceObj('ModDef', {
	'title', "The Monolith",
	'description', "<i>This construct, which can only be described as menacing, was found by one of our expeditions. We spared no effort and expense in hauling it close to our colony. Will it reveal it's secrets or was, bringing it here, an unforgivable mistake? // Joshua Kell, Principal Scientist, Mars Colony</i><br><br>\nAdds a new breakthrough and a recognizable building.\n<br><br>\n<i>(Special thanks go to akeean and ChoGGi!)</i>",
	'image', "UI/Thumbnail_TheMonolith3.png",
	'last_changes', "initial",
	'id', "mVhj034",
	'steam_id', "1661674622",
	'pops_desktop_uuid', "3af2b0a1-53ee-453b-ba33-9d2fc080bc79",
	'pops_any_uuid', "f7220c3e-fd26-4dc2-9b24-cd4d1ab649e9",
	'author', "Mil",
	'version', 35,
	'lua_revision', 233360,
	'saved_with_revision', 240905,
	'bin_assets', true,
	'code', {"Code/TheMonolith.lua"},
	'saved', 1550683937,
	'screenshot1', "UI/Screenshot0010.png",
	'screenshot2', "UI/Screenshot0009.png",
	'TagBuildings', true,
	'TagResearch', true,
})